/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package softwareproject;

import java.awt.Font;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adity
 */

public class Company extends javax.swing.JFrame {

    /**
     * Creates new form Company
     */
    public List< String>  test(int x)
    {
        if(Mainscreen.id==0 )
        {
            Mainscreen.id=x;
        }
        List<String> t=new ArrayList();
        table1.setFont(new Font("Calibri", Font.BOLD, 24));
        table1.setRowHeight(30);
        Statement st = SoftwareProject.invokedb();
        int cid, sid;
        String query = "select * from application,skills where application.companyid= " + Mainscreen.id + " and application.studentid=skills.studentid";
        System.out.println(query);
        try {
            ResultSet rs = st.executeQuery(query);
            DefaultTableModel model = (DefaultTableModel) table1.getModel();
            String[] arr = {"datascience", "mathematics", "programminglanguages", "machines", "nanotechnology", "physicalsciences", "semiconductors"};
           
           int k=0;
            while (rs.next()) {
                String roll = rs.getString(4);
                String s = "";
                for (int i = 5; i <= 11; i++) {
                    if (rs.getInt(i) != 0) {
                        s = s + arr[i - 5] + ", ";

                    }

                }
                Object[] arr2 = {roll, 0, s};
                t.add(roll);
                
                model.addRow(arr2);

            }
            

        } catch (Exception e) {
            System.err.println(e);
        }
        return t;
    }
    public Company() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        test(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N

        table1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        table1.setForeground(new java.awt.Color(255, 51, 102));
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "rollno", "cgpa", "skills"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table1.setToolTipText("<html> roll  ");
        jScrollPane1.setViewportView(table1);
        if (table1.getColumnModel().getColumnCount() > 0) {
            table1.getColumnModel().getColumn(0).setPreferredWidth(30);
        }

        jButton1.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jButton1.setText("Select Student");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int n1 = table1.getRowCount();
        int idx = -1;
        for (int i = 0; i < n1; i++) {
            if (table1.isRowSelected(i)) {
                int c = JOptionPane.showConfirmDialog(this, "Are you sure you want to selecct student " + table1.getValueAt(i, 0));
                if (c == JOptionPane.YES_OPTION) {
                    Statement stt = SoftwareProject.invokedb();
                    String findid = "select id from details where rolllno='" + table1.getValueAt(i, 0) + "'";
                    try {
                        ResultSet rs = stt.executeQuery(findid);
                        rs.next();
                        idx = rs.getInt(1);

                    } catch (Exception e) {
                        System.err.println(e);
                    }
                    String upd = "update application set status='shortlisted' where studentid=" + idx;
                    try {
                        stt.executeUpdate(upd);
                        System.out.println("Application confirmed");
                        JOptionPane.showMessageDialog(this, "Application Confirmed");

                    } catch (Exception e) {
                        System.err.println(e);
                    }

                }

            }

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Company().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table1;
    // End of variables declaration//GEN-END:variables
}
