/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package softwareproject;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JFrame;

import javax.swing.JOptionPane;

/**
 *
 * @author adity
 */
public class Mainscreen extends javax.swing.JFrame {

    public static int id;
    // new Jframe().setDefaultCloseOperation(Jframe.DISPOSE_ON_CLOSE);

    /**
     * Creates new form mainscreen
     */
    public void settext(int y)
    {
        String[] s={"adiabhi","adi2","adi3","adi4","adi5"};
        txt1.setText(s[y]);
        txt2.setText("1234");
        
        
    }
    public Mainscreen() {
        initComponents();
        getContentPane().setBackground(Color.white);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }
    public int login()
    {
        int flag=1;
               String s = txt1.getText();
        String t = txt2.getText();
        try {
            Statement stmt = SoftwareProject.invokedb();
            Statement st = SoftwareProject.invokedb2();
//here sonoo is database name, root is username and password  
            // Statement stmt=con.createStatement();
            String pass = "select * from logindetails where LoginId =\"" + s + "\"and Password = \"" + t + "\"";
            String pass2 = "select * from logincompany where loginid='" + s + "' and password='" + t + "'";
            System.out.println(pass);
            System.out.println(pass2);
            ResultSet rs = stmt.executeQuery(pass);
            ResultSet rs2 = st.executeQuery(pass2);
            if (rb1.isSelected()) {

                if (!rs.next()) {
                    flag=0;
                    JOptionPane.showMessageDialog(this, "Login UnSuccesful, Please Try Again");

                } else {
                    // if(rb1.isSelected())
                    //{
                    int idx = rs.getInt(1);

                    id = idx;
                    System.out.println("now id is " + id);
                    JOptionPane.showMessageDialog(this, "Login Succesful");
                    new Sttudent().setVisible(true);
                    this.setVisible(false);
                    //}
                    //else
                    {

                    }

                }
            } else if (rb2.isSelected()) {
                if (!rs2.next()) {
                    JOptionPane.showMessageDialog(this, "Login UnSuccesful, Please Try Again");

                } else {
                    // if(rb1.isSelected())
                    //{
                    int idx = rs2.getInt(3);

                    id = idx;
                    System.out.println("now id is " + id);
                    JOptionPane.showMessageDialog(this, "Login Succesful");
                    new Company().setVisible(true);
                    this.setVisible(false);
                    //}
                    //else
                    {

                    }

                }

            }
            else if(rb3.isSelected())
            {
                if(s.equals("admin") && t.equals("admin"))
                {
                    JOptionPane.showMessageDialog(this, "Login Successful");
                    new Admin().setVisible(true);
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Login Unsuccessful");
                        
                 }
                
                
                
            }

        } catch (HeadlessException | SQLException e) {
            System.err.println(e);
        }

        return flag;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane1 = new java.awt.ScrollPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        rb3 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(183, 161, 86));
        setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Californian FB", 0, 36)); // NOI18N
        jLabel1.setText("Student Login");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 0, 231, 72));

        txt1.setFont(new java.awt.Font("Californian FB", 0, 36)); // NOI18N
        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });
        getContentPane().add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 118, 187, -1));

        txt2.setFont(new java.awt.Font("Californian FB", 0, 36)); // NOI18N
        getContentPane().add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 195, 187, -1));

        jLabel2.setFont(new java.awt.Font("Californian FB", 0, 36)); // NOI18N
        jLabel2.setText("Login");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 121, -1, -1));

        jLabel3.setFont(new java.awt.Font("Californian FB", 0, 36)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 198, -1, -1));

        jButton1.setFont(new java.awt.Font("Californian FB", 0, 36)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 276, -1, -1));

        jButton2.setFont(new java.awt.Font("Californian FB", 0, 36)); // NOI18N
        jButton2.setText("Student Registration");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 276, -1, -1));

        buttonGroup1.add(rb1);
        rb1.setFont(new java.awt.Font("Californian FB", 0, 36)); // NOI18N
        rb1.setText("Student");
        getContentPane().add(rb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, -1, -1));

        buttonGroup1.add(rb2);
        rb2.setFont(new java.awt.Font("Californian FB", 0, 36)); // NOI18N
        rb2.setText("Company");
        getContentPane().add(rb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 55, -1, -1));

        jButton3.setFont(new java.awt.Font("Californian FB", 0, 36)); // NOI18N
        jButton3.setText("Company registration");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 276, 383, -1));

        buttonGroup1.add(rb3);
        rb3.setFont(new java.awt.Font("Californian FB", 0, 36)); // NOI18N
        rb3.setText("Admin");
        getContentPane().add(rb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1ActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    login();        // TODO add your handling code here:
 

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Register().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new Registercompany().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        // try{
        //</editor-fold>

        /* Create and display the form */
        // try{
        //    }catch(Exception e){System.out.println(e);};
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Mainscreen m = new Mainscreen();
                m.setVisible(true);
                m.setExtendedState(m.getExtendedState() | javax.swing.JFrame.MAXIMIZED_BOTH);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private java.awt.ScrollPane scrollPane1;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    // End of variables declaration//GEN-END:variables
}
